"""
PapayaStore Backend Bindings
"""

from __future__ import annotations
import datetime
import typing

__all__: list[str] = [
    "EntidadBase",
    "HeaderFile",
    "Producto",
    "ProductoRepository",
    "init_database",
]

class EntidadBase:
    def get_eliminado(self) -> bool: ...
    def get_fecha_creacion(self) -> datetime.datetime: ...
    def get_fecha_ultima_modificacion(self) -> datetime.datetime: ...
    def get_id(self) -> int: ...
    def get_nombre(self) -> str: ...
    def set_eliminado(self, arg0: bool) -> bool: ...
    def set_fecha_creacion(self, arg0: datetime.datetime) -> bool: ...
    def set_fecha_ultima_modificacion(
        self, arg0: datetime.datetime
    ) -> bool: ...
    def set_id(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> bool: ...
    def set_nombre(self, arg0: str) -> None: ...

class HeaderFile:
    @property
    def cantidad_registros(self) -> int: ...
    @cantidad_registros.setter
    def cantidad_registros(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def proximo_id(self) -> int: ...
    @proximo_id.setter
    def proximo_id(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def registros_activos(self) -> int: ...
    @registros_activos.setter
    def registros_activos(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def version(self) -> int: ...
    @version.setter
    def version(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...

class Producto(EntidadBase):
    def __init__(self) -> None: ...
    def get_codigo(self) -> str: ...
    def get_descripcion(self) -> str: ...
    def get_id_proveedor(self) -> int: ...
    def get_precio(self) -> float: ...
    def get_stock(self) -> int: ...
    def get_stock_minimo(self) -> int: ...
    def get_total_vendido(self) -> int: ...
    def set_codigo(self, arg0: str) -> None: ...
    def set_descripcion(self, arg0: str) -> None: ...
    def set_id_proveedor(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> bool: ...
    def set_precio(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> bool: ...
    def set_stock(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> bool: ...
    def set_stock_minimo(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> bool: ...
    def set_total_vendido(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> bool: ...

class ProductoRepository:
    def __init__(self) -> None: ...
    def actualizar(
        self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: Producto
    ) -> bool | str: ...
    def eliminar_logicamente(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> bool | str: ...
    def guardar(self, arg0: Producto) -> bool | str: ...
    def leer_por_id(
        self, arg0: typing.SupportsInt | typing.SupportsIndex
    ) -> papaya_backend.Producto | str: ...
    def leer_por_nombre(self, arg0: str) -> papaya_backend.Producto | str: ...
    def obtener_estadisticas(self) -> papaya_backend.HeaderFile | str: ...

def init_database() -> bool:
    """
    Inicializa la base de datos de archivos binarios
    """
