"""
PapayaStore Backend Bindings
"""
from __future__ import annotations
import datetime
import typing
__all__: list[str] = ['COMPRA', 'Cliente', 'ClienteRepository', 'DatabaseAdmin', 'EntidadBase', 'HeaderFile', 'PapayaContext', 'Producto', 'ProductoRepository', 'Proveedor', 'ProveedorRepository', 'Tienda', 'TipoDeTransaccion', 'Transaccion', 'TransaccionDTO', 'TransaccionRepository', 'VENTA', 'init_database']
class Cliente(EntidadBase):
    def __init__(self) -> None:
        ...
    def agregar_transaccion_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def get_cantidad(self) -> int:
        ...
    def get_cantidad_transacciones(self) -> int:
        ...
    def get_cedula(self) -> str:
        ...
    def get_direccion(self) -> str:
        ...
    def get_email(self) -> str:
        ...
    def get_historial_ids(self) -> list:
        ...
    def get_telefono(self) -> str:
        ...
    def get_total_compras(self) -> float:
        ...
    def get_transacciones_ids(self) -> list:
        ...
    def remover_transaccion_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_cantidad(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_cantidad_transacciones(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_cedula(self, arg0: str) -> bool:
        ...
    def set_direccion(self, arg0: str) -> bool:
        ...
    def set_email(self, arg0: str) -> bool:
        ...
    def set_historial_id_en_indice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_telefono(self, arg0: str) -> bool:
        ...
    def set_total_compras(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def set_transaccion_id_en_indice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
class ClienteRepository:
    def __init__(self) -> None:
        ...
    def actualizar(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: Cliente) -> bool | str:
        ...
    def eliminar_logicamente(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool | str:
        ...
    def guardar(self, arg0: Cliente) -> bool | str:
        ...
    def leer_por_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> papaya_backend.Cliente | str:
        ...
    def leer_por_nombre(self, arg0: str) -> papaya_backend.Cliente | str:
        ...
    def obtener_estadisticas(self) -> papaya_backend.HeaderFile | str:
        ...
class DatabaseAdmin:
    def crear_backup(self) -> None:
        ...
    def reporte_historial_cliente(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def reporte_stock_critico(self) -> int:
        ...
    def sincronizar_contadores_tienda(self) -> bool:
        ...
    def verificar_integridad_referencial(self) -> tuple[int, int, int, int]:
        ...
class EntidadBase:
    def get_eliminado(self) -> bool:
        ...
    def get_fecha_creacion(self) -> datetime.datetime:
        ...
    def get_fecha_ultima_modificacion(self) -> datetime.datetime:
        ...
    def get_id(self) -> int:
        ...
    def get_nombre(self) -> str:
        ...
    def set_eliminado(self, arg0: bool) -> bool:
        ...
    def set_fecha_creacion(self, arg0: datetime.datetime) -> bool:
        ...
    def set_fecha_ultima_modificacion(self, arg0: datetime.datetime) -> bool:
        ...
    def set_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_nombre(self, arg0: str) -> None:
        ...
class HeaderFile:
    @property
    def cantidad_registros(self) -> int:
        ...
    @cantidad_registros.setter
    def cantidad_registros(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def proximo_id(self) -> int:
        ...
    @proximo_id.setter
    def proximo_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def registros_activos(self) -> int:
        ...
    @registros_activos.setter
    def registros_activos(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def version(self) -> int:
        ...
    @version.setter
    def version(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class PapayaContext:
    def __init__(self) -> None:
        ...
    def init_database(self) -> bool:
        ...
    @property
    def admin(self) -> DatabaseAdmin:
        ...
    @property
    def clientes(self) -> ClienteRepository:
        ...
    @property
    def productos(self) -> ProductoRepository:
        ...
    @property
    def proveedores(self) -> ProveedorRepository:
        ...
    @property
    def transacciones(self) -> TransaccionRepository:
        ...
class Producto(EntidadBase):
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def get_codigo(self) -> str:
        ...
    def get_descripcion(self) -> str:
        ...
    def get_id_proveedor(self) -> int:
        ...
    def get_precio(self) -> float:
        ...
    def get_stock(self) -> int:
        ...
    def get_stock_minimo(self) -> int:
        ...
    def get_total_vendido(self) -> int:
        ...
    def set_codigo(self, arg0: str) -> None:
        ...
    def set_descripcion(self, arg0: str) -> None:
        ...
    def set_id_proveedor(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_precio(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def set_stock(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_stock_minimo(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_total_vendido(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
class ProductoRepository:
    def __init__(self) -> None:
        ...
    def actualizar(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: Producto) -> bool | str:
        ...
    def eliminar_logicamente(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool | str:
        ...
    def guardar(self, arg0: Producto) -> bool | str:
        ...
    def leer_por_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> papaya_backend.Producto | str:
        ...
    def leer_por_nombre(self, arg0: str) -> papaya_backend.Producto | str:
        ...
    def obtener_estadisticas(self) -> papaya_backend.HeaderFile | str:
        ...
class Proveedor(EntidadBase):
    def __init__(self) -> None:
        ...
    def get_cantidad(self) -> int:
        ...
    def get_cantidad_productos(self) -> int:
        ...
    def get_direccion(self) -> str:
        ...
    def get_email(self) -> str:
        ...
    def get_historial_ids(self) -> list:
        ...
    def get_productos_ids(self) -> list:
        ...
    def get_rif(self) -> str:
        ...
    def get_telefono(self) -> str:
        ...
    def set_cantidad(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_cantidad_productos(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_direccion(self, arg0: str) -> bool:
        ...
    def set_email(self, arg0: str) -> bool:
        ...
    def set_historial_id_en_indice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_producto_id_en_indice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_rif(self, arg0: str) -> bool:
        ...
    def set_telefono(self, arg0: str) -> bool:
        ...
class ProveedorRepository:
    def __init__(self) -> None:
        ...
    def actualizar(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: Proveedor) -> bool | str:
        ...
    def eliminar_logicamente(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool | str:
        ...
    def guardar(self, arg0: Proveedor) -> bool | str:
        ...
    def leer_por_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> papaya_backend.Proveedor | str:
        ...
    def leer_por_nombre(self, arg0: str) -> papaya_backend.Proveedor | str:
        ...
    def obtener_estadisticas(self) -> papaya_backend.HeaderFile | str:
        ...
class Tienda(EntidadBase):
    def __init__(self) -> None:
        ...
    def get_monto_total_compras(self) -> float:
        ...
    def get_monto_total_ventas(self) -> float:
        ...
    def get_rif(self) -> str:
        ...
    def get_total_clientes_activos(self) -> int:
        ...
    def get_total_productos_activos(self) -> int:
        ...
    def get_total_proveedores_activos(self) -> int:
        ...
    def get_total_transacciones_activas(self) -> int:
        ...
    def set_monto_total_compras(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def set_monto_total_ventas(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def set_rif(self, arg0: str) -> bool:
        ...
    def set_total_clientes_activos(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_total_productos_activos(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_total_proveedores_activos(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_total_transacciones_activas(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
class TipoDeTransaccion:
    """
    Members:
    
      COMPRA
    
      VENTA
    """
    COMPRA: typing.ClassVar[TipoDeTransaccion]  # value = <TipoDeTransaccion.COMPRA: 0>
    VENTA: typing.ClassVar[TipoDeTransaccion]  # value = <TipoDeTransaccion.VENTA: 1>
    __members__: typing.ClassVar[dict[str, TipoDeTransaccion]]  # value = {'COMPRA': <TipoDeTransaccion.COMPRA: 0>, 'VENTA': <TipoDeTransaccion.VENTA: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Transaccion(EntidadBase):
    def __init__(self) -> None:
        ...
    def get_descripcion(self) -> str:
        ...
    def get_id_relacionado(self) -> int:
        ...
    def get_producto_en_indice(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> TransaccionDTO:
        ...
    def get_productos(self) -> list:
        ...
    def get_productos_totales(self) -> int:
        ...
    def get_tipo_transaccion(self) -> TipoDeTransaccion:
        ...
    def get_total(self) -> float:
        ...
    def set_descripcion(self, arg0: str) -> bool:
        ...
    def set_id_relacionado(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_producto(self, arg0: TransaccionDTO) -> bool:
        ...
    def set_producto_en_indice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: TransaccionDTO) -> bool:
        ...
    def set_productos_totales(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_tipo_transaccion(self, arg0: TipoDeTransaccion) -> bool:
        ...
    def set_total(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
class TransaccionDTO:
    def __init__(self) -> None:
        ...
    @property
    def cantidad(self) -> int:
        ...
    @cantidad.setter
    def cantidad(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def precio(self) -> float:
        ...
    @precio.setter
    def precio(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def producto_id(self) -> int:
        ...
    @producto_id.setter
    def producto_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class TransaccionRepository:
    def __init__(self) -> None:
        ...
    def actualizar(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: Transaccion) -> bool | str:
        ...
    def eliminar_logicamente(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> bool | str:
        ...
    def guardar(self, arg0: Transaccion) -> bool | str:
        ...
    def leer_por_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> papaya_backend.Transaccion | str:
        ...
    def leer_por_nombre(self, arg0: str) -> papaya_backend.Transaccion | str:
        ...
    def obtener_estadisticas(self) -> papaya_backend.HeaderFile | str:
        ...
def init_database() -> bool:
    """
    Inicializa la base de datos de archivos binarios
    """
COMPRA: TipoDeTransaccion  # value = <TipoDeTransaccion.COMPRA: 0>
VENTA: TipoDeTransaccion  # value = <TipoDeTransaccion.VENTA: 1>
